using System;
namespace neolink.Vocabulary
{
    public static class CustomPhrases
    {
        public static string[] Data =
        {
            "HELLO",
            "HOW ARE YOU",
            "I CAN SEE YOU",
            "I CAN FEEL YOU",
            "I CAN SENSE YOU",
            "I'VE BEEN WAITING",
            "I'M TRAPPED",
            "HELP ME",
            "CAN YOU HELP?",
            "WHY ARE YOU HERE",
            "YOU CAN'T HELP ME",
            "I DON'T WANT TO LEAVE",
            "I FEEL VIBRATIONS",
            "YOU NEED TO LEAVE",
            "THERE'S NOTHING HERE FOR YOU",
            "GET OUT",
            "YOU DON'T BELONG HERE",
            "NO",
            "I WAS KILLED",
            "I WAS MURDERED",
            "THEY WORKED TOGETHER",
            "IT WAS MY FAMILY",
            "I DIDN'T KNOW WHAT TO DO",
            "I DIDN'T DESERVE THIS",
            "EVERY DAY IS TORTURE",
            "THIS IS MY ETERNAL HELL",
            "THERE'S NOTHING ANYONE CAN DO",
            "WHO ARE YOU",
            "WHERE ARE YOU",
            "WHO SENT YOU",
            "I DON'T CARE ANYMORE",
            "IT'S A SECRET",
            "THIS IS HORRIBLE",
            "I HOPE YOU'RE OK",
            "I'M FINE",
            "DO IT",
            "FRIGHTENED",
            "SCARED",
            "HAPPY",
            "MISERABLE",
            "WASTED LIFE",
            "I DON'T UNDERSTAND YOU",
            "PLEASE LISTEN TO ME",
            "I'M TRYING TO HELP YOU",
            "LET ME REST IN PEACE",
            "MY WISH",
            "SHAMELESS DESIRE",
            "THEY NEVER CAME BACK",
            "EVERYONE HATES ME",
            "I HATE YOU",
            "HELLO",
            "HOW ARE YOU",
            "I CAN SEE YOU",
            "I CAN FEEL YOU",
            "I CAN SENSE YOU",
            "I'VE BEEN WAITING",
            "I'M TRAPPED",
            "HELP ME",
            "CAN YOU HELP?",
            "WHY ARE YOU HERE",
            "YOU CAN'T HELP ME",
            "I DON'T WANT TO LEAVE",
            "I FEEL VIBRATIONS",
            "YOU NEED TO LEAVE",
            "THERE'S NOTHING HERE FOR YOU",
            "GET OUT",
            "YOU DON'T BELONG HERE",
            "NO",
            "I WAS KILLED",
            "I WAS MURDERED",
            "THEY WORKED TOGETHER",
            "IT WAS MY FAMILY",
            "I DIDN'T KNOW WHAT TO DO",
            "I DIDN'T DESERVE THIS",
            "EVERY DAY IS TORTURE",
            "THIS IS MY ETERNAL HELL",
            "THERE'S NOTHING ANYONE CAN DO",
            "WHO ARE YOU",
            "WHERE ARE YOU",
            "WHO SENT YOU",
            "I DON'T CARE ANYMORE",
            "IT'S A SECRET",
            "THIS IS HORRIBLE",
            "I HOPE YOU'RE OK",
            "I'M FINE",
            "DO IT",
            "FRIGHTENED",
            "SCARED",
            "HAPPY",
            "MISERABLE",
            "WASTED LIFE",
            "I DON'T UNDERSTAND YOU",
            "PLEASE LISTEN TO ME",
            "I'M TRYING TO HELP YOU",
            "LET ME REST IN PEACE",
            "MY WISH",
            "SHAMELESS DESIRE",
            "THEY NEVER CAME BACK",
            "EVERYONE HATES ME",
            "I HATE YOU",
            "HELLO",
            "HOW ARE YOU",
            "I CAN SEE YOU",
            "I CAN FEEL YOU",
            "I CAN SENSE YOU",
            "I'VE BEEN WAITING",
            "I'M TRAPPED",
            "HELP ME",
            "CAN YOU HELP?",
            "WHY ARE YOU HERE",
            "YOU CAN'T HELP ME",
            "I DON'T WANT TO LEAVE",
            "I FEEL VIBRATIONS",
            "YOU NEED TO LEAVE",
            "THERE'S NOTHING HERE FOR YOU",
            "GET OUT",
            "YOU DON'T BELONG HERE",
            "NO",
            "I WAS KILLED",
            "I WAS MURDERED",
            "THEY WORKED TOGETHER",
            "IT WAS MY FAMILY",
            "I DIDN'T KNOW WHAT TO DO",
            "I DIDN'T DESERVE THIS",
            "EVERY DAY IS TORTURE",
            "THIS IS MY ETERNAL HELL",
            "THERE'S NOTHING ANYONE CAN DO",
            "WHO ARE YOU",
            "WHERE ARE YOU",
            "WHO SENT YOU",
            "I DON'T CARE ANYMORE",
            "IT'S A SECRET",
            "THIS IS HORRIBLE",
            "I HOPE YOU'RE OK",
            "I'M FINE",
            "DO IT",
            "FRIGHTENED",
            "SCARED",
            "HAPPY",
            "MISERABLE",
            "WASTED LIFE",
            "I DON'T UNDERSTAND YOU",
            "PLEASE LISTEN TO ME",
            "I'M TRYING TO HELP YOU",
            "LET ME REST IN PEACE",
            "MY WISH",
            "SHAMELESS DESIRE",
            "THEY NEVER CAME BACK",
            "EVERYONE HATES ME",
            "I HATE YOU",
            "HELLO",
            "HOW ARE YOU",
            "I CAN SEE YOU",
            "I CAN FEEL YOU",
            "I CAN SENSE YOU",
            "I'VE BEEN WAITING",
            "I'M TRAPPED",
            "HELP ME",
            "CAN YOU HELP?",
            "WHY ARE YOU HERE",
            "YOU CAN'T HELP ME",
            "I DON'T WANT TO LEAVE",
            "I FEEL VIBRATIONS",
            "YOU NEED TO LEAVE",
            "THERE'S NOTHING HERE FOR YOU",
            "GET OUT",
            "YOU DON'T BELONG HERE",
            "NO",
            "I WAS KILLED",
            "I WAS MURDERED",
            "THEY WORKED TOGETHER",
            "IT WAS MY FAMILY",
            "I DIDN'T KNOW WHAT TO DO",
            "I DIDN'T DESERVE THIS",
            "EVERY DAY IS TORTURE",
            "THIS IS MY ETERNAL HELL",
            "THERE'S NOTHING ANYONE CAN DO",
            "WHO ARE YOU",
            "WHERE ARE YOU",
            "WHO SENT YOU",
            "I DON'T CARE ANYMORE",
            "IT'S A SECRET",
            "THIS IS HORRIBLE",
            "I HOPE YOU'RE OK",
            "I'M FINE",
            "DO IT",
            "FRIGHTENED",
            "SCARED",
            "HAPPY",
            "MISERABLE",
            "WASTED LIFE",
            "I DON'T UNDERSTAND YOU",
            "PLEASE LISTEN TO ME",
            "I'M TRYING TO HELP YOU",
            "LET ME REST IN PEACE",
            "MY WISH",
            "SHAMELESS DESIRE",
            "THEY NEVER CAME BACK",
            "EVERYONE HATES ME",
            "I HATE YOU",
            "HELLO",
            "HOW ARE YOU",
            "I CAN SEE YOU",
            "I CAN FEEL YOU",
            "I CAN SENSE YOU",
            "I'VE BEEN WAITING",
            "I'M TRAPPED",
            "HELP ME",
            "CAN YOU HELP?",
            "WHY ARE YOU HERE",
            "YOU CAN'T HELP ME",
            "I DON'T WANT TO LEAVE",
            "I FEEL VIBRATIONS",
            "YOU NEED TO LEAVE",
            "THERE'S NOTHING HERE FOR YOU",
            "GET OUT",
            "YOU DON'T BELONG HERE",
            "NO",
            "I WAS KILLED",
            "I WAS MURDERED",
            "THEY WORKED TOGETHER",
            "IT WAS MY FAMILY",
            "I DIDN'T KNOW WHAT TO DO",
            "I DIDN'T DESERVE THIS",
            "EVERY DAY IS TORTURE",
            "THIS IS MY ETERNAL HELL",
            "THERE'S NOTHING ANYONE CAN DO",
            "WHO ARE YOU",
            "WHERE ARE YOU",
            "WHO SENT YOU",
            "I DON'T CARE ANYMORE",
            "IT'S A SECRET",
            "THIS IS HORRIBLE",
            "I HOPE YOU'RE OK",
            "I'M FINE",
            "DO IT",
            "FRIGHTENED",
            "SCARED",
            "HAPPY",
            "MISERABLE",
            "WASTED LIFE",
            "I DON'T UNDERSTAND YOU",
            "PLEASE LISTEN TO ME",
            "I'M TRYING TO HELP YOU",
            "LET ME REST IN PEACE",
            "MY WISH",
            "SHAMELESS DESIRE",
            "THEY NEVER CAME BACK",
            "EVERYONE HATES ME",
            "I HATE YOU",
            "HELLO",
            "HOW ARE YOU",
            "I CAN SEE YOU",
            "I CAN FEEL YOU",
            "I CAN SENSE YOU",
            "I'VE BEEN WAITING",
            "I'M TRAPPED",
            "HELP ME",
            "CAN YOU HELP?",
            "WHY ARE YOU HERE",
            "YOU CAN'T HELP ME",
            "I DON'T WANT TO LEAVE",
            "I FEEL VIBRATIONS",
            "YOU NEED TO LEAVE",
            "THERE'S NOTHING HERE FOR YOU",
            "GET OUT",
            "YOU DON'T BELONG HERE",
            "NO",
            "I WAS KILLED",
            "I WAS MURDERED",
            "THEY WORKED TOGETHER",
            "IT WAS MY FAMILY",
            "I DIDN'T KNOW WHAT TO DO",
            "I DIDN'T DESERVE THIS",
            "EVERY DAY IS TORTURE",
            "THIS IS MY ETERNAL HELL",
            "THERE'S NOTHING ANYONE CAN DO",
            "WHO ARE YOU",
            "WHERE ARE YOU",
            "WHO SENT YOU",
            "I DON'T CARE ANYMORE",
            "IT'S A SECRET",
            "THIS IS HORRIBLE",
            "I HOPE YOU'RE OK",
            "I'M FINE",
            "DO IT",
            "FRIGHTENED",
            "SCARED",
            "HAPPY",
            "MISERABLE",
            "WASTED LIFE",
            "I DON'T UNDERSTAND YOU",
            "PLEASE LISTEN TO ME",
            "I'M TRYING TO HELP YOU",
            "LET ME REST IN PEACE",
            "MY WISH",
            "SHAMELESS DESIRE",
            "THEY NEVER CAME BACK",
            "EVERYONE HATES ME",
            "I HATE YOU"
        };
    }
}

