using System;
namespace neolink.Vocabulary
{
    public static class PrepositionIn
    {
        public static string[] Data =
        {
            "ABSORBED IN MEDITATION",
            "ATONE IN MEASURE",
            "BARREN IN INTELLECT",
            "BASKING IN SUNSHINE",
            "BURIED IN SOLITUDE",
            "CALL IN QUESTION",
            "CLOTHED IN TRUTH",
            "CONFIDENT IN OPINION",
            "CONFUTE IN ARGUMENT",
            "CONTEMPLATIVE IN ASPECT",
            "DEFICIENT IN INSIGHT",
            "DELIGHT IN LEARNING",
            "DETERIORATION IN QUALITY",
            "DIFFERENCE IN DETAIL",
            "DILIGENT IN APPLICATION",
            "DIMINISH IN RESPECT",
            "DWARFED IN NUMBERS",
            "END IN SMOKE",
            "ENUMERATE IN DETAIL",
            "EXPERIENCED IN DUPLICITY",
            "FEEBLE IN INFLUENCE",
            "FERTILE IN CONSEQUENCE",
            "FLOURISH IN LUXURIANCE",
            "FOUNDED IN TRUTH",
            "GAZE IN ASTONISHMENT",
            "GO IN PURSUIT",
            "GRACEFUL IN PROPORTION",
            "GRIEVOUSLY IN ERROR",
            "HOLD IN BONDAGE",
            "IMMERSED IN THOUGHT",
            "INDULGE IN REVERIE",
            "INFERIOR IN CHARACTER",
            "INFLUENTIAL IN SOCIETY",
            "INGENUITY IN PLANNING",
            "INSTANCE IN POINT",
            "INVOLVED IN OBSCURITY",
            "LANDMARKS IN MEMORY",
            "LANGUISH IN OBSCURITY",
            "LIE IN WAIT",
            "LIMITED IN SCOPE",
            "LINGER IN EXPECTATION",
            "LISTEN IN AMAZEMENT",
            "LOST IN AWE",
            "LOWER IN ESTIMATION",
            "LUXURIANT IN FANCY",
            "MONSTROUS IN DULNESS",
            "MYSTERIOUS IN ORIGIN",
            "NOBLE IN AMPLITUDE",
            "NURSED IN LUXURY",
            "ORGANIZED IN THOUGHT",
            "PETULANT IN EXPRESSION",
            "PLEAD IN VAIN",
            "PLEASING IN OUTLINE",
            "PLUNGED IN DARKNESS",
            "POSITIVE IN JUDGMENT",
            "PRACTICAL IN APPLICATION",
            "PRIDE IN SUCCESS",
            "PROTEST IN VAIN",
            "PURSUED IN LEISURE",
            "QUICK IN SUGGESTION",
            "READY IN RESOURCE",
            "RECOILING IN TERROR",
            "REMOTE IN CHARACTER",
            "REVEL IN DANGER",
            "RICH IN VARIETY",
            "ROOTED IN PREJUDICE",
            "SCHOOLED IN SELF-RESTRAINT",
            "SCRUPULOUS IN CONDUCT",
            "SET IN MOTION",
            "SKILLED IN CONTROVERSY",
            "SOUND IN THEORY",
            "STAMMER IN CONFUSION",
            "STRICKEN IN YEARS",
            "STRIDES IN CIVILIZATION",
            "STRIKING IN CHARACTER",
            "STUNTED IN GROWTH",
            "TENDER IN SENTIMEN",
            "UNIQUE IN LITERATURE",
            "UNITY IN DIVERSITY",
            "UNPRECEDENTED IN KIND",
            "VERSED IN KNOWLEDGE",
            "WALLOW IN IDOLATRY",
            "WANTING IN DIGNITY",
            "WAVER IN PURPOSE",
            "WEAK IN CONCEPTION"
        };
    }
}

