using System;
namespace neolink.Vocabulary
{
    public static class PrepositionBy
    {
        public static string[] Data =
        {
            "AFFECTED BY EXTERNALS",
            "ALLAYED BY SYMPATHY",
            "ANIMATED BY VICTORY",
            "APPRAISED BY FASHION",
            "ASSAILED BY CONSCIENCE",
            "ATTAINED BY EFFORT",
            "AVERT BY PRAYER",
            "BALLASTED BY BRAINS",
            "BESET BY DIFFICULTIES",
            "BOUND BY OPINION",
            "BRANDED BY DEFEAT",
            "CHARACTERIZED BY DISCRETION",
            "CHASTENED BY SORROW",
            "CHEEK BY JOWL",
            "CIRCULATED BY MALICE",
            "CLOGGED BY INSINCERITY",
            "COLORED BY ENVIRONMENT",
            "CONDEMNED BY POSTERITY",
            "CONFIRMED BY HABIT",
            "CONSOLED BY PRAYER",
            "CONVINCED BY ARGUMENT",
            "CONVULSED BY DIVISIONS",
            "DARKENED BY SHADOWS",
            "DAZZLED BY FAME",
            "DEPRAVED BY PAIN",
            "DEVOURED BY CURIOSITY",
            "DISGUSTED BY SERVILITY",
            "DRIVEN BY REMORSE",
            "EMBARRASSED BY TIMIDITY",
            "ENCOURAGED BY SUCCESS",
            "ENFEEBLED BY AGE",
            "ENFORCED BY ACTION",
            "ENJOINED BY RELIGION",
            "ENRICHED BY GIFTS",
            "ESTABLISHED BY CONVENTION",
            "EVOKED BY SHAME",
            "FASCINATED, BY MYSTERY",
            "FAVORED BY FORTUNE",
            "FETTERED BY SYSTEMS",
            "FIRED BY WRATH",
            "FORBID BY AUTHORITY",
            "FORTIFIED BY FAITH",
            "GOVERNED BY PRECEDENT",
            "GUIDED BY INSTINCT",
            "HAUNTED BY VISIONS",
            "HUSHED BY DENIAL",
            "IMPELLED BY DUTY",
            "INCULCATED BY PRACTISE",
            "INDUCED BY MISREPRESENTATION",
            "INFLUENCED BY CAUTION",
            "INSPIRED BY LOVE",
            "LEARNED BY ROTE",
            "MARKED BY ACUTENESS",
            "MEASURED BY YEARS",
            "NARROWED BY CUSTOM",
            "OCCASIONED BY IRRITATION",
            "OPPRESSED BY DESTINY",
            "PARCHED BY DISUSE",
            "PERSUADED BY APPEAL",
            "PORTRAY BY WORDS",
            "PRESCRIBED BY CUSTOM",
            "PREVENTED BY CHANCE",
            "PROMPTED BY COQUETRY",
            "PURGED BY SORROW",
            "RACKED BY SUFFERING",
            "REFUTED BY REASON",
            "REPELLED BY CENSURE",
            "RESTRAINED BY VIOLENCE",
            "RISING BY INDUSTRY",
            "SANCTIONED BY EXPERIENCE",
            "SHAPED BY TRADITION",
            "SOURED BY MISFORTUNE",
            "STUNG BY DERISION",
            "SUPPLANTED BY OTHERS",
            "SUPPORTED BY EVIDENCE",
            "THWARTED BY FORTUNE",
            "TEMPERED BY CHARITY",
            "TORMENTED BY JEALOUSY",
            "TORTURED BY DOUBT",
            "UNADORNED BY ARTIFICE",
            "UNDAUNTED BY FAILURE",
            "UNDETERMINED BY SORROW",
            "UNDONE BY TREACHERY",
            "UNFETTERED BY FEAR",
            "URGED BY CURIOSITY",
            "VITALIZED BY THOUGHT",
            "WON BY AGGRESSION",
            "WORN BY TIME",
            "WRENCHED BY EMOTIONS"
        };
    }
}

