using System;
namespace neolink.Vocabulary
{
    public static class PrepositionTo
    {
        public static string[] Data =
        {
            "ADDICTED TO FLATTERY",
            "ADHERENCE TO PRINCIPLE",
            "AFFECT TO BELIEVE",
            "AKIN TO TRUTH",
            "ALIVE TO OPPORTUNITY",
            "ALLIED TO VIRTUE",
            "AMENABLE TO REASON",
            "ASPIRE TO RULE",
            "ATTEMPT TO SUPPRESS",
            "AVERSION TO PUBLICITY",
            "BLIND TO DEMONSTRATION",
            "BROUGHT TO REPENTANCE",
            "CLAIM TO PERPETUITY",
            "COME TO NOTHING",
            "COMMITTED TO RIGHTEOUSNESS",
            "COMMON TO HUMANITY",
            "CONDUCIVE TO HAPPINESS",
            "CONFORMABLE TO FACT",
            "CONSIGNED TO OBLIVION",
            "CONSTRAINED TO SPEAK",
            "CONTRIBUTION TO KNOWLEDGE",
            "DEAF TO ENTREATY",
            "DEDICATED TO FRIENDSHIP",
            "DEFERENCE TO CUSTOM",
            "DEVOTED TO IDEALS",
            "DOOMED TO DESTRUCTION",
            "DRIVEN TO DESPAIR",
            "DWARF TO UNIMPORTANCE",
            "EMPOWERED TO ACT",
            "ENDEARED TO ALL",
            "EXCITE TO PITY",
            "EXPOSED TO DERISION",
            "FLY TO PLATITUDES",
            "FOREDOOMED TO FAILURE",
            "GIVEN TO EXTRAVAGANCE",
            "GROUND TO ATOMS",
            "HARASSED TO DEATH",
            "HOSTILE TO PROGRESS",
            "IMPERVIOUS TO SUGGESTION",
            "IMPOSSIBLE TO RECONCILE",
            "IMPOTENT TO SAVE",
            "INCENTIVE TO DEVOTION",
            "INCITEMENT TO ANGER",
            "INCLINED TO VASCILLATE",
            "INDIFFERENCE TO TRUTH",
            "INTENT TO DECEIVE",
            "INTOLERABLE TO SOCIETY",
            "INVOCATION TO SLEEP",
            "LAUGH TO SCORN",
            "LEFT TO CONJECTURE",
            "LOST TO REMEMBRANCE",
            "OBEDIENCE TO CONSCIENCE",
            "OBLIVIOUS TO CRITICISM",
            "OFFENSIVE TO MODESTY",
            "OPEN TO REASON",
            "OPPOSED TO INNOVATION",
            "PANDER TO PREJUDICE",
            "PERTAINING TO FASHION",
            "PRONE TO MELANCHOLY",
            "PROPOSE TO UNDERTAKE",
            "PROVOKE TO LAUGHTER",
            "PUT TO CONFUSION",
            "RECOURSE TO FALSEHOOD",
            "REDUCED TO IMPOTENCE",
            "RELATED TO ETERNITY",
            "REPEAT TO SATIETY",
            "REPUGNANT TO JUSTICE",
            "REQUISITE TO SUCCESS",
            "RESORT TO VIOLENCE",
            "RUN TO SEED",
            "SEEK TO OVERAWE",
            "SERVE TO EMBITTER",
            "SPUR TO ACTION",
            "STIMULUS TO AMBITION",
            "STIRRED TO REMONSTRANCE",
            "SUBJECT TO SCRUTINY",
            "SUCCUMB TO FASCINATION",
            "SUPERIOR TO CIRCUMSTANCES",
            "SUSCEPTIBLE TO ARGUMENT",
            "TEMPTATION TO DOUBT",
            "TEND TO FRUSTRATE",
            "TRUST TO CHANCE",
            "UTILIZE TO ADVANTAGE",
            "VENTURE TO SAY",
            "VITAL TO SUCCESS",
            "WEDDED TO ANTIQUITY",
            "YIELD TO REASON"
        };
    }
}

