using System;
namespace neolink.Vocabulary
{
    public class PrepositionWith
    {
        public static string[] Data =
        {
            "ABOUNDING WITH PLENTY",
            "ACCORD WITH NATURE",
            "ACT WITH DELIBERATION",
            "ADORN WITH BEAUTY",
            "AFFLICT WITH UGLINESS",
            "AFLAME WITH LIFE",
            "ALLIED WITH ECONOMY",
            "ANTICIPATE WITH DELIGHT",
            "ASCERTAIN WITH EXACTNESS",
            "ATTENDED WITH DANGER",
            "BEAM WITH SELF-APPROVAL",
            "BEHAVE WITH SERVILITY",
            "BIG WITH FATE",
            "BLINDED WITH TEARS",
            "BLUSH WITH SHAME",
            "BRANDED WITH COWARDICE",
            "BUBBLING WITH LAUGHTER",
            "BURN WITH INDIGNATION",
            "CLING WITH TENACITY",
            "CLOTHE WITH AUTHORITY",
            "COMPATIBLE WITH FREEDOM",
            "COMPLY WITH TRADITION",
            "CONCEAL WITH DIFFICULTY",
            "CONSISTENT WITH FACTS",
            "COVERED WITH IGNOMINY",
            "CRUSH WITH SORROW",
            "DENY WITH EMPHASIS",
            "DEPRESSED WITH FEAR",
            "DISPENSE WITH FORMALITY",
            "DISTORT WITH PASSION",
            "ECHO WITH MERRIMENT",
            "ENDOW WITH INTELLIGENCE",
            "ENDURE WITH FORTITUDE",
            "EXAMINE WITH CURIOSITY",
            "FACE WITH INDIFFERENCE",
            "FLUSHED WITH PRIDE",
            "FRAUGHT WITH PERIL",
            "FURIOUS WITH INDIGNATION",
            "GLOWING WITH DELIGHT",
            "IMBUED WITH COURAGE",
            "INCOMPATIBLE WITH REASON",
            "INCONSISTENT WITH BEAUTY",
            "INFLAMED WITH RAGE",
            "INSPIRED WITH PATRIOTISM",
            "INTOXICATED WITH JOY",
            "KINDLE WITH ENTHUSIASM",
            "LAUGH WITH GLEE",
            "MEET WITH REBUKE",
            "MINGLED WITH CURIOSITY",
            "MOVE WITH ALACRITY",
            "OPPRESSED WITH HARDSHIP",
            "OVERCOME WITH SHYNESS",
            "OVERFLOWING WITH LOVE",
            "OVERHUNG WITH GLOOM",
            "PERFORMED WITH REGULARITY",
            "PERVADED WITH GRANDEUR",
            "PROCEED WITH ALERTNESS",
            "PUNISH WITH SEVERITY",
            "QUICKEN WITH PRIDE",
            "QUIVER WITH ANXIETY",
            "RADIANT WITH VICTORY",
            "REGARD WITH LOATHING",
            "RELATE WITH ZEST",
            "REPEL WITH INDIGNATION",
            "SADDLE WITH RESPONSIBILITY",
            "SCREAM WITH TERROR",
            "SICK WITH DREAD",
            "SOB WITH ANGUISH",
            "SQUIRM WITH DELIGHT",
            "SUFFUSE WITH SPIRITUALITY",
            "TAINTED WITH FRAUD",
            "TEEMING WITH LIFE",
            "TENSE WITH EXPECTANCY",
            "THRILL WITH EXCITEMENT",
            "THROB WITH VITALITY",
            "TINGED WITH ROMANCE",
            "TOUCHED WITH FEELING",
            "TREAT WITH CONTEMPT",
            "TREMBLE WITH FEAR",
            "UNMIXED WITH EMOTION",
            "UTTER WITH SARCASM",
            "VIBRANT WITH FEELING",
            "VIEW WITH AWE",
            "WIELD WITH POWER",
            "WORK WITH ZEAL"
        };
    }
}

