using System;
namespace neolink.Vocabulary
{
    public static class PrepositionInto
    {
        public static string[] Data =
        {
            "ABASHED INTO SILENCE",
            "BEGUILE INTO READING",
            "BETRAY INTO SPEECH",
            "BLENDING INTO HARMONY",
            "BRING INTO DISREPUTE",
            "BULLIED INTO SILENCE",
            "BURN INTO MEMORY",
            "BURST INTO VIEW",
            "CALL INTO QUESTION",
            "CARRY INTO CONFLICT",
            "CHILL INTO APATHY",
            "COMING INTO VOGUE",
            "CRINGE INTO FAVOR",
            "CRUMBLED INTO DUST",
            "CRYSTALLIZED INTO ACTION",
            "DASH INTO FRAGMENTS",
            "DEEPEN INTO CONFUSION",
            "DEGENERATE INTO MONOTONY",
            "DELUDED INTO BELIEVING",
            "DESCENT INTO DEATH",
            "DISSOLVE INTO NOTHINGNESS",
            "DRAGGED INTO PURSUIT",
            "DRAWN INTO CONTROVERSY",
            "DRIBBLING INTO WORDS",
            "DRIVEN INTO SERVITUDE",
            "DULLED INTO ACQUIESCENCE",
            "ELECTRIFY INTO ACTIVITY",
            "ELEVATED INTO IMPORTANCE",
            "ENQUIRE INTO PRECEDENTS",
            "ENTER INTO CONTROVERSY",
            "EXPAND INTO WEAKNESS",
            "FADE INTO INSIGNIFICANCE",
            "FALL INTO DECAY",
            "FASHION INTO FESTOONS",
            "FLAME INTO WAR",
            "FLOWER INTO SYMPATHY",
            "FORCED INTO ACTION",
            "FROZEN INTO FORM",
            "FUSE INTO UNITY",
            "GALVANIZE INTO LIFE",
            "GO INTO RAPTURES",
            "GOADED INTO ACTION",
            "HUSHED INTO SILENCE",
            "INCURSIONS INTO CONTROVERSY",
            "INSIGHT INTO TRUTH",
            "KINDLE INTO ACTION",
            "LASH INTO SILENCE",
            "LAUNCH INTO DISAPPROVAL",
            "LEAD INTO CAPTIVITY",
            "LEAP INTO CURRENCY",
            "LULLED INTO INDIFFERENCE",
            "MELT INTO SPACE",
            "MERGE INTO CHARACTER",
            "PASS INTO OBLIVION",
            "PLUNGE INTO DESPAIR",
            "POUR INTO PRINT",
            "QUICKEN INTO LIFE",
            "RELAPSE INTO SAVAGERY",
            "RENDERED INTO MUSIC",
            "RESOLVE INTO NOTHINGNESS",
            "RETREAT INTO SILENCE",
            "RIPENED INTO LOVE",
            "RUSH INTO PRINT",
            "SHOCKED INTO ATTENTION",
            "SINK INTO INSIGNIFICANCE",
            "SMITTEN INTO ICE",
            "SNUBBED INTO QUIESCENCE",
            "STRICKEN INTO SILENCE",
            "SUMMONED INTO BEING",
            "SWOLLEN INTO TORRENTS",
            "TAKE INTO ACCOUNT",
            "THROWN INTO DISORDER",
            "TRANSFORM INTO BEAUTY",
            "TRANSLATED INTO FACT",
            "USHER INTO SOCIETY",
            "VANISH INTO MYSTERY",
            "WANDER INTO DIGRESSION",
            "WHEEDLED INTO ACQUIESCENCE",
            "WITHDRAW INTO SOLITUDE"
        };
    }
}

